export enum TypePokemon {
  Grass = "grass",
  Poison = "poison",
  Fire = "fire",
  Flying = "flying",
  Water = "water",
  Bug = "bug",
  Normal = "normal",
  Dark = "dark",
  Electric = "electric",
  Psychic = "psychic",
  Ground = "ground",
  Ice = "ice",
  Steel = "steel",
  Fairy = "fairy",
  Fighting = "fighting",
  Rock = "rock",
  Ghost = "ghost",
  Dragon = "dragon",
}
